### ISSUE TITLE
Crash while "Save Current Results"

### ISSUE THREAD

**Issue by RossBoylan** [bifs/bifs#16]
Loaded a 3D image in bifs_gui, ran the map with default parameters and selected "Save Current Results".  Boom!

```
Saving Current Results
Traceback (most recent call last):
  File "bifs\src\bifs_gui.py", line 432, in saveCurrent
    self.mybifs.save_results()
  File "C:\Users\rdboylan\Documents\Kornak\bifs\bifs\src\bifs.py", line 286, in save_results
    plt.imsave(out_im,self.final_image,cmap = cm.Greys_r)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\matplotlib\pyplot.py", line 2140, in imsave
    return matplotlib.image.imsave(fname, arr, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\matplotlib\image.py", line 1496, in imsave
    rgba = sm.to_rgba(arr, bytes=True)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\matplotlib\cm.py", line 268, in to_rgba
    raise ValueError("third dimension must be 3 or 4")
ValueError: third dimension must be 3 or 4
```

@kyoung21b Did this ever work?  Did 2d or 1d versions ever work?

I get this running in debug mode in Visual Studio 2019 Preview and when running from the command prompt with py -3 bifs_gui.py.

**Comment by RossBoylan** [comment]
This exact code no longer exists.  In particular, `self.final_image` is a function; it generally should be, and is currently, `self.final_image()`.

 But problems persist, even with ~~the 2D test image misleadingly called~~ `test3Dnoisy_sphere.tiff`:
```
Uncaught exception:
   File "J:\source\repos\bifs\bifs\bifsexception.py", line 134, in wrapper
    return function(self)
  File "J:\source\repos\bifs\bifs\bifs_gui.py", line 433, in saveCurrent
    if not self.mybifs.final_image():

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "J:\source\repos\bifs\bifs\bifsexception.py", line 134, in wrapper
    return function(self)
  File "J:\source\repos\bifs\bifs\bifs_gui.py", line 433, in saveCurrent
    if not self.mybifs.final_image():
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by RossBoylan** [comment]
After fixing previous bug, we return to roughly the original error:

```
Traceback (most recent call last):
  File "J:\source\repos\bifs\bifs\bifsexception.py", line 134, in wrapper
    return function(self)
  File "J:\source\repos\bifs\bifs\bifs_gui.py", line 438, in saveCurrent
    self.mybifs.save_results()
  File "J:\source\repos\bifs\bifs\bifscore.py", line 291, in save_results
    plt.imsave(out_im,self.final_image(),cmap = cm.Greys_r)
  File "J:\source\repos\bifs\env\lib\site-packages\matplotlib\pyplot.py", line 2412, in imsave
    return matplotlib.image.imsave(fname, arr, **kwargs)
  File "J:\source\repos\bifs\env\lib\site-packages\matplotlib\image.py", line 1582, in imsave
    rgba = sm.to_rgba(arr, bytes=True)
  File "J:\source\repos\bifs\env\lib\site-packages\matplotlib\cm.py", line 338, in to_rgba
    raise ValueError("Third dimension must be 3 or 4")
ValueError: Third dimension must be 3 or 4
```

maptlotlib.image.imsave says

> arr (2nd arg) arrarray-like
>
>    The image data. The shape can be one of MxN (luminance), MxNx3 (RGB) or MxNx4 (RGBA).

But the image is 32x32x32 so

1. apparently it is 3d
2. obviously the routine can not cope with 3d images

**Comment by RossBoylan** [comment]
d4a786a7acb4b55829266d57e4f2ae3159a70a30 provides a more informative error message saying only 2D is supported.
Not a fix, but at least a clarification.

**Comment by RossBoylan** [comment]
BTW, bifs_gui mostly doesn't go boom anymore; it pops up a notification that an operation has failed, along with clues about what went wrong.
